import { BRAKE_AMBIENT_TEMP_C, BRAKE_MATERIALS, brakeCoolingRatePerS } from "./brakeModel";
import { deriveDriverInputs } from "./driverModel";
import { buildEngineCurves } from "./engineModel";
import { buildLongitudinalModel, computeSpeedProfile } from "./speedProfile";
import { deriveVehicle } from "./vehicleModel";
import {
  Circuit,
  ChassisConfig,
  EngineConfig,
  GearboxConfig,
  SimulationResult,
  Telemetry,
  TestConfig,
} from "./types";
import { G, estimateTopSpeedKph } from "./vehicleDynamics";

// Mechanical + driver delay per gear change: a manual needs a clutch and a
// physical lever throw, a torque-converter/single-clutch auto is quicker,
// and a dual-clutch box is close to instantaneous. Applied as dead time
// added directly to the lap clock at every gear change, rather than
// modeled inside the speed-position solve (which works in distance, not
// time, and doesn't need discrete events to find the fastest achievable
// speed at each point).
const MANUAL_SHIFT_TIME_S = 0.25;
const DUAL_CLUTCH_SHIFT_TIME_S = 0.05;
const AUTO_SHIFT_TIME_S = 0.15;

// Below this speed, a distance-domain dt = ds / v integration blows up
// numerically. A hot lap's speed profile should never actually get this
// low (see UNCONSTRAINED_SPEED_MS/cornering-limit floor in
// speedProfile.ts) - this only guards against pathological configurations
// (e.g. near-zero grip) so the simulation stays finite instead of
// producing Infinity/NaN lap times.
const MIN_INTEGRATION_SPEED_MS = 0.3;

function shiftTimeS(gearbox: GearboxConfig): number {
  if (gearbox.transmissionType === "manual") return MANUAL_SHIFT_TIME_S;
  return gearbox.dualClutch ? DUAL_CLUTCH_SHIFT_TIME_S : AUTO_SHIFT_TIME_S;
}

// One theoretical flying lap of a circuit, calculated (not guessed) end to
// end:
//
//   vehicle config -> engine/gearbox -> wheel force -> tyre limits
//   -> aerodynamics -> braking/acceleration -> circuit curvature
//   -> virtual driver -> speed profile -> telemetry -> lap time
//
// circuit.points already carries distance/heading/curvature derived purely
// from the track's geometry (circuitGeometry.ts); this function's job is to
// find the fastest speed the car can carry at every one of those points
// (computeSpeedProfile), turn that into per-point pedal/gear inputs
// (deriveDriverInputs), and integrate dt = ds / v along the lap to get both
// the telemetry trace and the final lap time - never the other way around.
export function simulateHotLap(
  engine: EngineConfig,
  chassis: ChassisConfig,
  gearbox: GearboxConfig,
  test: TestConfig,
  circuit: Circuit,
): SimulationResult {
  const curves = buildEngineCurves(engine);
  const vehicle = deriveVehicle(engine, curves, chassis, gearbox);
  const model = buildLongitudinalModel(vehicle, chassis, curves, test);

  const profile = computeSpeedProfile(circuit.points, vehicle, model);
  const inputs = deriveDriverInputs(profile, vehicle, curves, model);

  const n = profile.length;
  const ds = n > 1 ? profile[1].distanceM - profile[0].distanceM : circuit.lengthM;

  let t = 0;
  let brakeTempC = test.initialBrakeTempC;
  const brakeMaterial = BRAKE_MATERIALS[test.brakeMaterial];
  let prevGear = inputs[0]?.gear ?? 1;

  const telemetry: Telemetry[] = [];

  for (let i = 0; i < n; i++) {
    const point = profile[i];
    const input = inputs[i];

    if (input.gear !== prevGear) {
      t += shiftTimeS(gearbox);
      prevGear = input.gear;
    }

    const integrationSpeedMs = Math.max(MIN_INTEGRATION_SPEED_MS, point.speedMs);
    const dt = ds / integrationSpeedMs;
    t += dt;

    // Air cooling relaxes the brakes toward ambient every step - faster at
    // speed on a straight, slower through a slow corner - then any heat
    // generated by braking this step piles back on top.
    const coolingRatePerS = brakeCoolingRatePerS(point.speedMs);
    brakeTempC = BRAKE_AMBIENT_TEMP_C + (brakeTempC - BRAKE_AMBIENT_TEMP_C) * Math.exp(-coolingRatePerS * dt);
    if (input.brakeForceN > 0) {
      brakeTempC += (input.brakeForceN * ds) / brakeMaterial.thermalMassJPerC;
    }

    telemetry.push({
      t,
      speedKph: point.speedMs * 3.6,
      rpm: input.rpm,
      gear: input.gear,
      hp: curves.powerAt(input.rpm),
      torqueNm: input.torqueNm,
      gForce: input.accelMs2 / G,
      distanceM: point.distanceM,
      brakeTempC,
      brakeForceN: input.brakeForceN,
      lateralGForce: (point.speedMs * point.speedMs * point.curvature) / G,
      throttle: input.throttle,
      brakeInput: input.brakeInput,
      tyreUtilization: input.tyreUtilization,
      downforceN: input.downforceN,
      dragN: input.dragN,
      curvature: point.curvature,
    });
  }

  const last = telemetry[telemetry.length - 1] ?? null;

  return {
    telemetry,
    testType: "hotLap",
    initialSpeedKph: profile[0]?.speedMs !== undefined ? profile[0].speedMs * 3.6 : 0,
    elapsedS: t,
    finalSpeedKph: last?.speedKph ?? 0,
    finalDistanceM: circuit.lengthM,
    reachedHundredAtS: null,
    timedOut: false,
    peakHp: curves.peakPowerHp,
    peakHpRpm: curves.peakPowerRpm,
    peakTorqueNm: curves.peakTorqueNm,
    peakTorqueRpm: curves.peakTorqueRpm,
    weightKg: vehicle.weightKg,
    powerToWeightHpPerTonne: curves.peakPowerHp / (vehicle.weightKg / 1000),
    theoreticalTopSpeedKph: estimateTopSpeedKph(curves, vehicle, 0),
    circuitId: circuit.id,
  };
}
